class LawFirmMailer < ApplicationMailer

  def account_creation_confirmation(law_firm)
  	@law_firm = law_firm
  	mail(to: law_firm.email, subject: "Your account has been successfully created")
  end

  def firm_decertified(law_firm)
  	@law_firm = law_firm
  	@user = @law_firm.try(:user)
  	mail(to: @law_firm.relationship_manager_email, subject: "#{@law_firm.name} has been decertified")
  end

  def initial_submissions_generated(law_firm)
  	@law_firm = law_firm
  	@user = @law_firm.try(:user)
  	mail(to: @law_firm.email, subject: "SEAL process started")
  end

  def decision_reached(form_submission, decision)
  	subject = ""
  	@law_firm = form_submission.law_firm
  	@user = @law_firm.try(:user)
  	if decision == 'Follow Up'
  		subject = "Admin has requested a follow up on your recent submission"
  	else
  		subject = "Your recent SEAL submission has been #{decision}"
  	end
  	mail(to: @user.email, subject: subject)
  end

  def security_threat_generated(law_firm_id)
  	@law_firm = LawFirm.find_by(id: law_firm_id)
    if @law_firm
    	@user = @law_firm.try(:user)
    	mail(to: @law_firm.email, subject: "A security threat has been generated by the admin")
    end
  end

  def invite_user(user, temp_password, law_firm)
    @user = user
    @temp_password = temp_password
    @law_firm = law_firm
    mail(to: @user.email, subject: "#{@law_firm.name} invited you to join SEAL")
  end

end
