class AddDocusignAccessTokenToSystemSettings < ActiveRecord::Migration[5.0]
  def up
    add_column :system_settings, :docusign_access_token, :text

    system_setting = SystemSetting.fetch
    system_setting.docusign_access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjY4MTg1ZmYxLTRlNTEtNGNlOS1hZjFjLTY4OTgxMjIwMzMxNyJ9.eyJUb2tlblR5cGUiOjUsIklzc3VlSW5zdGFudCI6MTU2OTk0NzI5NCwiZXhwIjoxNTY5OTc2MDk0LCJVc2VySWQiOiI5NzIwMWE0My0zNDZlLTQ2ZjItYWExZC0yNDUxMjlhZjcxZjAiLCJzaXRlaWQiOjEsInNjcCI6WyJzaWduYXR1cmUiLCJjbGljay5tYW5hZ2UiLCJvcmdhbml6YXRpb25fcmVhZCIsImdyb3VwX3JlYWQiLCJwZXJtaXNzaW9uX3JlYWQiLCJ1c2VyX3JlYWQiLCJ1c2VyX3dyaXRlIiwiYWNjb3VudF9yZWFkIiwiZG9tYWluX3JlYWQiLCJpZGVudGl0eV9wcm92aWRlcl9yZWFkIiwiZHRyLnJvb21zLnJlYWQiLCJkdHIucm9vbXMud3JpdGUiLCJkdHIuZG9jdW1lbnRzLnJlYWQiLCJkdHIuZG9jdW1lbnRzLndyaXRlIiwiZHRyLnByb2ZpbGUucmVhZCIsImR0ci5wcm9maWxlLndyaXRlIiwiZHRyLmNvbXBhbnkucmVhZCIsImR0ci5jb21wYW55LndyaXRlIl0sImF1ZCI6ImYwZjI3ZjBlLTg1N2QtNGE3MS1hNGRhLTMyY2VjYWUzYTk3OCIsImlzcyI6Imh0dHBzOi8vYWNjb3VudC1kLmRvY3VzaWduLmNvbS8iLCJzdWIiOiI5NzIwMWE0My0zNDZlLTQ2ZjItYWExZC0yNDUxMjlhZjcxZjAiLCJhbXIiOlsiaW50ZXJhY3RpdmUiXSwiYXV0aF90aW1lIjoxNTY5OTQ3MjkyLCJwd2lkIjoiZGY1ZDM1OGYtM2MwOC00ZmMyLWJiZGUtNGE5ZThjZmU3NjkxIn0.keCZYlqJdmLTa_vDve9_vySAI7QJJBizEBzLIVcgmw5wgxljtJHpkurseVPBJuG32fyGsSwsMTyzTvpEr9Lv4EPqU5hiFan-VXbtx32SfKcVpUc5SVdFqVFDtCzYtEPCCTEMKav5QibYa0SOrHi9h44UjbHNK-iWmbwb9T7X3mCPlrOZ4ZsklhplWfV17nfqlysR5d9KN8WFl-IYl6Zq0KSPzWS3GmXYZ-GvRYXZeIbeLhWMFTWrV_DlSkKJHYviW6NPHlcAsP__dX9QaPHfQ1RKWL-EB1aDk-cmqo6uH3w9Nin95jDUL7XAx5LJIs1Y-fNA7lfkFDvyqi5lOgXe3Q"
    system_setting.save
  end

  def down
    remove_column :system_settings, :docusign_access_token
  end
end
